name: CI

on: ["push"]

jobs:
  check_linter_and_tests:
    name: Create/update todos
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: default_environment
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.1'
      - name: Install dependencies
        run: npm i
      - name: Check for Linting Violations
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run Tests
        run: npm run tests
